/* Shared semantic colours, labels and formatters. */
export type RiskLevel = "LOW" | "MODERATE" | "HIGH" | "VERY_HIGH" | "CRITICAL";
export type AlertLevel = "GREEN" | "YELLOW" | "ORANGE" | "RED";
export type DrainState = "NORMAL" | "HIGH_LOAD" | "NEAR_CAPACITY" | "OVERLOADED" | "OVERFLOW";

export const RISK_COLORS: Record<string, string> = {
  LOW: "#16a34a", MODERATE: "#eab308", HIGH: "#f97316", VERY_HIGH: "#dc2626", CRITICAL: "#9f1239",
};
export const ALERT_COLORS: Record<string, string> = { GREEN: "#16a34a", YELLOW: "#eab308", ORANGE: "#f97316", RED: "#dc2626" };
export const DRAIN_COLORS: Record<string, string> = {
  NORMAL: "#16a34a", HIGH_LOAD: "#84cc16", NEAR_CAPACITY: "#eab308", OVERLOADED: "#f97316", OVERFLOW: "#dc2626",
};
export const FACILITY_STATUS_COLORS: Record<string, string> = {
  OPERATIONAL: "#16a34a", AT_RISK: "#eab308", ACCESS_RESTRICTED: "#f97316", ISOLATED: "#dc2626", FLOODED: "#9f1239",
};
export const PASSABILITY_COLORS: Record<string, string> = {
  PASSABLE: "#16a34a", PASSABLE_WITH_CAUTION: "#84cc16", UNSAFE_LIGHT_VEHICLES: "#eab308",
  EMERGENCY_VEHICLES_ONLY: "#f97316", IMPASSABLE: "#dc2626",
};
export const REPORT_STATUS_COLORS: Record<string, string> = {
  VERIFIED: "#16a34a", UNVERIFIED: "#64748b", UNDER_REVIEW: "#eab308", RESOLVED: "#0ea5e9",
};
export const INCIDENT_STATUS_COLORS: Record<string, string> = {
  OPEN: "#dc2626", ACKNOWLEDGED: "#f97316", IN_PROGRESS: "#eab308", RESOLVED: "#16a34a",
};
export const MAINT_COLORS: Record<string, string> = { REPAIR: "#dc2626", CLEAN: "#f97316", INSPECT: "#eab308", MONITOR: "#16a34a" };

export const DATA_LABELS: Record<string, { text: string; color: string; hint: string }> = {
  LIVE_DATA: { text: "LIVE DATA", color: "#16a34a", hint: "Real-time value from an external live source" },
  HISTORICAL_DATA: { text: "HISTORICAL DATA", color: "#6366f1", hint: "Recorded past observations" },
  SIMULATED_DATA: { text: "SIMULATED DATA", color: "#a855f7", hint: "Generated by deterministic software simulation — not a measurement" },
  DEMO_DATA: { text: "DEMO DATA", color: "#64748b", hint: "Synthetic demonstration dataset — replace with municipal data" },
  MODEL_PREDICTION: { text: "MODEL PREDICTION", color: "#0ea5e9", hint: "Output of FloodShield AI models — a forecast, not an observation" },
  USER_REPORTED_DATA: { text: "USER-REPORTED", color: "#f59e0b", hint: "Submitted by citizens / uploaded media — may be unverified" },
};

export const pretty = (s?: string | null) => (s ? s.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()) : "—");
export const fmt = (v: any, d = 1, unit = "") => (v === null || v === undefined || Number.isNaN(v) ? "—" : `${Number(v).toFixed(d)}${unit}`);
export const pct = (v: any, d = 0) => (v === null || v === undefined ? "—" : `${(Number(v) * 100).toFixed(d)}%`);
export const depth = (m: any) => (m === null || m === undefined ? "—" : Number(m) >= 1 ? `${Number(m).toFixed(2)} m` : `${Math.round(Number(m) * 100)} cm`);
export const ttf = (m: number | null | undefined) => (m === null || m === undefined ? "Not expected" : m === 0 ? "Flooded now" : `in ${m} min`);

export const FACILITY_LABELS: Record<string, string> = {
  hospital: "Hospitals", police: "Police", fire_station: "Fire stations", school: "Schools", railway_station: "Railway / Metro",
  bus_terminal: "Bus terminals", shelter: "Shelters", substation: "Power substations", government: "Government offices",
};

/* colour ramps (value -> css colour) */
function lerp(a: number[], b: number[], t: number) {
  return a.map((x, i) => Math.round(x + (b[i] - x) * t));
}
function ramp(stops: [number, number[]][]) {
  return (v: number): [number, number, number, number] => {
    if (v <= stops[0][0]) return [...stops[0][1], 255] as any;
    for (let i = 1; i < stops.length; i++) {
      if (v <= stops[i][0]) {
        const t = (v - stops[i - 1][0]) / (stops[i][0] - stops[i - 1][0]);
        return [...lerp(stops[i - 1][1], stops[i][1], t), 255] as any;
      }
    }
    return [...stops[stops.length - 1][1], 255] as any;
  };
}
export const RAMPS = {
  rain: ramp([[0.5, [191, 219, 254]], [10, [96, 165, 250]], [30, [37, 99, 235]], [60, [124, 58, 237]], [100, [219, 39, 119]], [150, [220, 38, 38]]]),
  rainAccum: ramp([[1, [224, 242, 254]], [50, [56, 189, 248]], [150, [37, 99, 235]], [300, [88, 28, 135]]]),
  depth: ramp([[0.02, [186, 230, 253]], [0.1, [56, 189, 248]], [0.3, [37, 99, 235]], [0.5, [30, 64, 175]], [0.8, [88, 28, 135]], [1.5, [59, 7, 100]]]),
  probability: ramp([[0.1, [254, 240, 138]], [0.4, [251, 191, 36]], [0.7, [249, 115, 22]], [1.0, [220, 38, 38]]]),
  elevation: ramp([[0, [21, 128, 61]], [0.35, [132, 204, 22]], [0.6, [234, 179, 8]], [0.8, [180, 83, 9]], [1, [245, 245, 244]]]),
  slope: ramp([[0, [240, 253, 244]], [2, [134, 239, 172]], [5, [250, 204, 21]], [10, [234, 88, 12]], [20, [127, 29, 29]]]),
  runoff: ramp([[1, [254, 249, 195]], [10, [250, 204, 21]], [25, [249, 115, 22]], [50, [220, 38, 38]], [90, [127, 29, 29]]]),
  flowAcc: ramp([[0, [240, 249, 255]], [1, [125, 211, 252]], [2, [2, 132, 199]], [3.3, [12, 74, 110]]]),
  impervious: ramp([[0, [22, 163, 74]], [0.5, [250, 204, 21]], [1, [71, 85, 105]]]),
  diff: ramp([[-0.5, [22, 163, 74]], [0, [241, 245, 249]], [0.3, [249, 115, 22]], [1, [159, 18, 57]]]),
};
export const LANDCOVER_COLORS: Record<number, number[]> = {
  1: [100, 116, 139], 2: [251, 191, 36], 3: [239, 68, 68], 4: [34, 197, 94], 5: [14, 165, 233], 6: [180, 83, 9],
};
